[package]
name = "burn-lab1-part2"
version = "0.1.0"
edition = "2021"
rust-version = "1.77.2"
readme = "README.md"

[dependencies]
argh = "0.1"
burn = { version = "0.13.2", features = ["train", "tch"] }
burn-import = "0.13"
fastrand = "2"
log = "0.4"
rand = "0.8"
regex = "1"
tch = "0.15"
